export const FETCH_JOBS = "FETCH_JOBS";
export const APPLY_JOB = "APPLY_JOB";

export const FETCH_USERS = "FETCH_USER";
export const GET_RESUME = "GET_RESUME";

export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const LOGOUT = "LOGOUT";
export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";

export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SIGNUP_SUCESS = "SIGNUP_SUCESS";
export const LOGIN_SUCESS = "LOGIN_SUCESS";

//eroor action types
export const RETURN_ERRORS = "RETURN_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//user actions
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const CLEAR_USER_PROFILE = "CLEAR_USER_PROFILE";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";

// company action
export const SET_COMPANY_PROFILE = "SET_COMPANY_PROFILE";
export const CLEAR_COMPANY_PROFILE = "CLEAR_COMPANY_PROFILE";
export const CREATE_COMPANY_PROFILE_INFO = "CREATE_COMPANY_PROFILE_INFO";

export const ADD_COMPANY_JOB_OFFER = "ADD_COMPANY_JOB_OFFER";
export const UPDATE_COMPANY_JOB_OFFER = "UPDATE_COMPANY_JOB_OFFER";
export const DELETE_COMPANY_JOB_OFFER = "DELETE_COMPANY_JOB_OFFER";

export const ADD_COMPANY_JOB_OFFER_WITH_SKILLS =
  "ADD_COMPANY_JOB_OFFER_WITH_SKILLS";

export const DELETE_COMPANY_JOB_OFFER_SKILL = "DELETE_COMPANY_JOB_OFFER_SKILL";

export const ADD_COMPANY_JOB_OFFER_SKILL = "ADD_COMPANY_JOB_OFFER_SKILL";
export const ADD_COMPANY_JOB_OFFER_SKILLS = "ADD_COMPANY_JOB_OFFER_SKILLS";

export const SEARCH_COMPANY_JOB_OFFER = "SEARCH_COMPANY_JOB_OFFER";
export const FILTER_COMPANY_JOB_OFFER = "FILTER_COMPANY_JOB_OFFER";

// Application Job
export const FETCH_COMPANY_JOB_APPLICATIONS = "FETCH_COMPANY_JOB_APPLICATIONS";
export const FETCH_CANDIDATE_DETAILS = "FETCH_CANDIDATE_DETAILS";
export const ACCEPT_REJECT_CANDIATE = "ACCEPT_REJECT_CANDIATE";

// job_details
export const FETCH_JOB_DETAILS = "FETCH_JOB_DETAILS";
export const SET_DEFAULT_JOB_DETAILS = "SET_DEFAULT_JOB_DETAILS";

// Resume_Actions

//Add
export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const ADD_EDUCATION = "ADD_EDUCATION";
export const ADD_PROJECT = "ADD_PROJECT";
export const ADD_LANGUAGE = "ADD_LANGUAGE";
export const ADD_SKILL = "ADD_SKILL";
export const ADD_INTEREST = "ADD_INTEREST";
export const ADD_CERTIFICATE = "ADD_CERTIFICATE";
export const ADD_AWARD = "ADD_AWARD";

//Delete
export const DEL_EXPERIENCE = "DEL_EXPERIENCE";
export const DEL_EDUCATION = "DEL_EDUCATION";
export const DEL_PROJECT = "DEL_PROJECT";
export const DEL_LANGUAGE = "DEL_LANGUAGE";
export const DEL_SKILL = "DEL_SKILL";
export const DEL_INTEREST = "DEL_INTEREST";
export const DEL_CERTIFICATE = "DEL_CERTIFICATE";
export const DEL_AWARD = "DEL_AWARD";

//Update
export const UPDATE_EXPERIENCE = "UPDATE_EXPERIENCE";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";
export const UPDATE_SKILL = "UPDATE_SKILL";
export const UPDATE_INTEREST = "UPDATE_INTEREST";
export const UPDATE_CERTIFICATE = "UPDATE_CERTIFICATE";
export const UPDATE_AWARD = "UPDATE_AWARD";

//UI_Actions
export const SET_PROFILE_SECTION = "SET_PROFILE_SECTION";
export const SET_PAGE = "SET_PAGE";
export const SET_LIMIT = "SET_LIMIT";
export const SET_QUERY_TERM = "SET_QUERY_TERM";
export const SET_DATA_LENGTH = "SET_DATA_LENGTH";
export const SET_WIZARD_FORM = "SET_WIZARD_FORM";

export const SET_WIZARD_FORM_FIRST_INFO = "SET_WIZARD_FORM_FIRST_INFO";
export const SET_WIZARD_FORM_FIRST_RESUME_INFO =
  "SET_WIZARD_FORM_FIRST_RESUME_INFO";
export const SET_WIZARD_FORM_FIRST_EXPERIENCE =
  "SET_WIZARD_FORM_FIRST_EXPERIENCE";

export const SET_WIZARD_FORM_FIRST_EDUCATION =
  "SET_WIZARD_FORM_FIRST_EDUCATION";
export const SET_WIZARD_FORM_FIRST_SKILL = "SET_WIZARD_FORM_FIRST_SKILL";

export const CLEAR_WIZARD_FORM_DATA = "CLEAR_WIZARD_FORM_DATA";
